#!/bin/bash

# Install Python to the location given as an argument

set -e
set -u
set -o pipefail

dest="$1"

if [[ ! ${dest} =~ ^/.* ]]; then
    echo "$0: Argument must be an absolute path" >&2
    exit 1
fi

python_url=https://www.python.org/ftp/python/3.7.7/Python-3.7.7.tgz

python_archive_name=${python_url##*/}
python_archive_path=$dest/build/${python_archive_name}
mkdir -p $dest/build

if [ ! -r ${python_archive_path} ]; then
    curl --output ${python_archive_path} ${python_url}
fi

cd $dest/build
tar xfz ${python_archive_name}
python_name=${python_archive_name%.tgz}
cd ${python_name}
./configure --prefix=${dest}/${python_name}
make -j 8 install

echo
echo "Select this Python installation using:"
echo "  export PATH=${dest}/${python_name}/bin:\$PATH"
echo
